In [ ]:
'''
85일간 100개의 건물들을 24시간(1시간 단위) 관찰
'''

In [ ]:
import pandas as pd
import numpy as np
train = pd.read_csv('/content/drive/MyDrive/electric/train.csv')
test = pd.read_csv('/content/drive/MyDrive/electric/test.csv')
info = pd.read_csv('/content/drive/MyDrive/electric/building_info.csv')
sub = pd.read_csv('/content/drive/MyDrive/electric/sample_submission.csv')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204000 entries, 0 to 203999
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   num_date_time  204000 non-null  object
 1   건물번호           204000 non-null  int64
 2   일시             204000 non-null  object
 3   기온(C)          204000 non-null  float64
 4   강수량(mm)        43931 non-null   float64
 5   풍속(m/s)        203981 non-null  float64
 6   습도(%)          203991 non-null  float64
 7   일조(hr)         128818 non-null  float64
 8   일사(MJ/m2)      116087 non-null  float64
 9   전력소비량(kWh)     204000 non-null  float64
dtypes: float64(7), int64(1), object(2)
memory usage: 15.6+ MB

In [ ]:
train.head() #0시 ~ 23시까지

,num_date_time,건물번호,일시,기온(C),강수량(mm),풍속(m/s),습도(%),일조(hr),일사(MJ/m2),전력소비량(kWh)
0,1_20220601 00,1,20220601 00,18.6,NaN,0.9,42.0,NaN,NaN,1085.28
1,1_20220601 01,1,20220601 01,18.0,NaN,1.1,45.0,NaN,NaN,1047.36
2,1_20220601 02,1,20220601 02,17.7,NaN,1.5,45.0,NaN,NaN,974.88
3,1_20220601 03,1,20220601 03,16.7,NaN,1.4,48.0,NaN,NaN,953.76
4,1_20220601 04,1,20220601 04,18.4,NaN,2.8,43.0,NaN,NaN,986.40

In [ ]:
train.tail()

,num_date_time,건물번호,일시,기온(C),강수량(mm),풍속(m/s),습도(%),일조(hr),일사(MJ/m2),전력소비량(kWh)
203995,100_20220824 19,100,20220824 19,23.1,NaN,0.9,86.0,0.5,NaN,881.04
203996,100_20220824 20,100,20220824 20,22.4,NaN,1.3,86.0,0.0,NaN,798.96
203997,100_20220824 21,100,20220824 21,21.3,NaN,1.0,92.0,NaN,NaN,825.12
203998,100_20220824 22,100,20220824 22,21.0,NaN,0.3,94.0,NaN,NaN,640.08
203999,100_20220824 23,100,20220824 23,20.7,NaN,0.1,95.0,NaN,NaN,540.24

In [21]:
filtered_train = train[train['num_date_time'].astype(str).str.startswith('4_')]
filtered_train

,num_date_time,건물번호,일시,기온(C),강수량(mm),풍속(m/s),습도(%),일조(hr),일사(MJ/m2),전력소비량(kWh)
6120,4_20220601 00,4,20220601 00,18.6,NaN,0.9,42.0,NaN,NaN,740.16
6121,4_20220601 01,4,20220601 01,18.0,NaN,1.1,45.0,NaN,NaN,671.04
6122,4_20220601 02,4,20220601 02,17.7,NaN,1.5,45.0,NaN,NaN,619.20
6123,4_20220601 03,4,20220601 03,16.7,NaN,1.4,48.0,NaN,NaN,626.40
6124,4_20220601 04,4,20220601 04,18.4,NaN,2.8,43.0,NaN,NaN,626.22
...,...,...,...,...,...,...,...,...,...,...
8155,4_20220824 19,4,20220824 19,25.5,NaN,2.9,63.0,0.1,0.19,847.08
8156,4_20220824 20,4,20220824 20,25.0,NaN,2.6,66.0,0.0,0.01,782.10
8157,4_20220824 21,4,20220824 21,24.6,NaN,1.3,67.0,NaN,NaN,751.86
8158,4_20220824 22,4,20220824 22,24.1,NaN,2.1,70.0,NaN,NaN,763.56
8159,4_20220824 23,4,20220824 23,23.8,NaN,1.4,70.0,NaN,NaN,719.64

In [22]:
filtered_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2040 entries, 6120 to 8159
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   num_date_time  2040 non-null   object
 1   건물번호           2040 non-null   int64
 2   일시             2040 non-null   object
 3   기온(C)          2040 non-null   float64
 4   강수량(mm)        501 non-null    float64
 5   풍속(m/s)        2040 non-null   float64
 6   습도(%)          2040 non-null   float64
 7   일조(hr)         1273 non-null   float64
 8   일사(MJ/m2)      1273 non-null   float64
 9   전력소비량(kWh)     2040 non-null   float64
dtypes: float64(7), int64(1), object(2)
memory usage: 175.3+ KB

In [ ]:
info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   건물번호          100 non-null    int64
 1   건물유형          100 non-null    object
 2   연면적(m2)       100 non-null    float64
 3   냉방면적(m2)      100 non-null    float64
 4   태양광용량(kW)     100 non-null    object
 5   ESS저장용량(kWh)  100 non-null    object
 6   PCS용량(kW)     100 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB

In [ ]:
info.head()

   건물번호  건물유형    연면적(m2)   냉방면적(m2) 태양광용량(kW) ESS저장용량(kWh) PCS용량(kW)
0     1  건물기타  110634.00   39570.00         -            -         -
1     2  건물기타  122233.47   99000.00         -            -         -
2     3  건물기타  171243.00  113950.00        40            -         -
3     4  건물기타   74312.98   34419.62        60            -         -
4     5  건물기타  205884.00  150000.00         -         2557      1000